### ISSUE TITLE
Segmentation Faults Galore

### ISSUE THREAD

**Issue by pjobson** [OnionIoT/fast-gpio#4]
Running the latest: 0.1.9 (b149)

set-output - segfaults galore

    root@Omega-ADBD:~# fast-gpio set-output 1
    Segmentation fault
    root@Omega-ADBD:~# fast-gpio set-output 2
    Segmentation fault
    root@Omega-ADBD:~# fast-gpio set-output 3
    Segmentation fault
    root@Omega-ADBD:~# fast-gpio set-output 4
    Segmentation fault
    root@Omega-ADBD:~# fast-gpio set-output 5
    Segmentation fault
    root@Omega-ADBD:~# fast-gpio set-output 6
    Segmentation fault

set-input - segfaults galore

    root@Omega-ADBD:~# fast-gpio set-input 1
    Segmentation fault
    root@Omega-ADBD:~# fast-gpio set-input 2
    Segmentation fault
    root@Omega-ADBD:~# fast-gpio set-input 3
    Segmentation fault
    root@Omega-ADBD:~# fast-gpio set-input 4
    Segmentation fault
    root@Omega-ADBD:~# fast-gpio set-input 5
    Segmentation fault
    root@Omega-ADBD:~# fast-gpio set-input 6
    Segmentation fault

get-direction - segfaults galore

    root@Omega-ADBD:~# fast-gpio get-direction 1
    Segmentation fault
    root@Omega-ADBD:~# fast-gpio get-direction 2
    Segmentation fault
    root@Omega-ADBD:~# fast-gpio get-direction 3
    Segmentation fault
    root@Omega-ADBD:~# fast-gpio get-direction 4
    Segmentation fault
    root@Omega-ADBD:~# fast-gpio get-direction 5
    Segmentation fault
    root@Omega-ADBD:~# fast-gpio get-direction 6
    Segmentation fault

read - you guessed it

    root@Omega-ADBD:~# fast-gpio read 1
    Segmentation fault
    root@Omega-ADBD:~# fast-gpio read 2
    Segmentation fault
    root@Omega-ADBD:~# fast-gpio read 3
    Segmentation fault
    root@Omega-ADBD:~# fast-gpio read 4
    Segmentation fault
    root@Omega-ADBD:~# fast-gpio read 5
    Segmentation fault
    root@Omega-ADBD:~# fast-gpio read 6
    Segmentation fault

set - this one is a load of fun the usage comes up weird.

    root@Omega-ADBD:~# fast-gpio
    Usage:
        fast-gpio set-input <gpio>
        fast-gpio set-output <gpio>
        fast-gpio get-direction <gpio>
        fast-gpio read <gpio>
        fast-gpio set <gpio> <value: 0 or 1>
        fast-gpio pwm <gpio> <freq in Hz> <duty cycle percentage>
        fast-gpio pulses <gpio> <path_pulses_file> <repeats>

    root@Omega-ADBD:~# fast-gpio set 1
    Usage:
        set set-input <gpio>
        set set-output <gpio>
        set get-direction <gpio>
        set read <gpio>
        set set <gpio> <value: 0 or 1>
        set pwm <gpio> <freq in Hz> <duty cycle percentage>
        set pulses <gpio> <path_pulses_file> <repeats>

**Comment by greenbreakfast** [comment]
Yep, there is a firmware issue that causes `fast-gpio` to seg fault, we're working on it!

It's listed as one of the known issues in the firmware: https://docs.onion.io/omega2-docs/known-firmware-issues.html

**Comment by greenbreakfast** [comment]
Fixed in firmware b160: https://docs.onion.io/omega2-docs/known-firmware-issues.html
